### ISSUE TITLE
onSubmit callback does not return errors set manually

### ISSUE THREAD

**Issue by MarceloPrado** [derekstavis/react-vanilla-form#39] opened 2019-08-21 21:07 UTC
When trying to do async validations (eg "email already in use"), one has to manually pass down `errors` prop, **as the lib currently does not allow returning Promises from validation functions.**

I noticed a strange behaviour: **`onSubmit` callback does not return errors set manually**. This causes a lot of "wiring" among lib users trying to achieve more complex validations.

I created a simple [repo](https://github.com/MarceloPrado/react-vanilla-form-errors-prop-issue) reproducing what I believe to be some sort of bug.

Here's a screenshot of the mentioned issue. In the example, two inputs (`postalCode` and `asyncPostalCode`) have their errors manually set. Seeing the `onSubmit` callback, you can notice the lib passed down just the `validations` errors and ignored our custom set `errors` prop.

![Screenshot 2019-08-21 17 21 19](https://user-images.githubusercontent.com/8047841/63467764-8a5ddd80-c43c-11e9-982b-b2a0220e60dc.png)

Is this the intended behaviour?

If not, I can create a PR addressing thes issue. I was also thinking about adding support for async validation, as it would reduce the boilerplate necessary for achieving these validations - @derekstavis what do you think?

**Comment by derekstavis** [comment] 2019-08-23 06:17
I believe this is not the intended behavior. The errors set through the prop should be merged with the errors when the `onSubmit` callback fires!

I'm glad to publish a new version if you send a PR with the fix! Please make sure to add tests as well to ensure there's no regression.

Thank you so much for filing this issue!

**Closed** 2019-08-29 15:59 UTC
